/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionNotificaciones.h"
#include <string.h>
bool_t *
enviarnotificacion_1_svc(char **argp, struct svc_req *rqstp)
{
	static bool_t  result;
    if(strcmp(*argp,"")!=0){
        printf("\n%s\n",*argp);
        result = TRUE;
    }else{
        result = FALSE;
    }
    return &result;
}
