/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include "gestionPersonal.h"
#include <string.h>
#include <ctype.h>

void clear_newlines(void);
int esAlfanumerica(char *cadena);

int esAlfanumerica(char *cadena)
{
	int i;
	int tieneLetra = 0;
	int tieneNumero = 0;
	for (i = 0; i < strlen(cadena); i++)
	{
		char letra = cadena[i];
		if (isalpha(letra))
		{
			tieneLetra = 1;
		}
		if (isdigit(letra))
		{
			tieneNumero = 1;
		}
	}
	return tieneLetra && tieneNumero;
}

void
gestion_personal_1(char *host)
{
	CLIENT *clnt;
    
	bool_t  *result_1;
	datos_personal  registrarpersonal_1_arg;
	
    datos_personal  *result_2;
	int  consultarpersonal_1_arg;
	
    bool_t  *result_3;
	datos_credencial  abrirsesion_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_personal, gestion_personal_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    int op=0, op1=0, op2=0;
    char* admin_username = "ingesis";
    char* admin_password = "ingesis";
    do
	{
        char username[MAXDAT];
        char password[MAXDAT];
		printf("\n\n======== Menú  Inicio =========\n");
		printf("* 1.-Abrir sesión.            *\n");
		printf("* 2.-Salir.                   *\n");
		printf("===============================\n");
		printf("Seleccione una opcion: ");
		scanf("%d", &op);
        clear_newlines();
        switch(op)
		{
			case 1:
            
			printf("\n======== Abrir  sesión ========\n");
			printf("Ingrese el nombre de usuario: ");
			scanf("%s", &username);
            printf("Ingrese la contraseña del usuario: ");
			scanf("%s", &password);
            strcpy(abrirsesion_1_arg.usuario, username);
            strcpy(abrirsesion_1_arg.clave, password);
            
            result_3 = abrirsesion_1(&abrirsesion_1_arg, clnt);
            if (result_3 == (bool_t *) NULL) {
                clnt_perror (clnt, "call ABRIR SESION failed");
            }
            
            if((strcmp(username,admin_username)==0) && (strcmp(password, admin_password)==0)){
                do{
                    int es_valido=1;
                    printf("\n\n========= Menú Admin ==========\n");
                    printf("* 1.-Registrar personal       *\n");
                    printf("* 2.-Consultar personal       *\n");
                    printf("* 3.-Salir                    *\n");
                    printf("===============================\n");
                    printf("Seleccione una opcion: ");
                    scanf("%d", &op1);
                    clear_newlines();
                    switch(op1){
                        case 1:
                            printf("\n===== Registrar  Personal =====");
                            printf("\nIngrese el tipo de identificación[cc, ti, pp]: ");
                            scanf("%s", &registrarpersonal_1_arg.tipoId);
                            
                            if(strcmp(registrarpersonal_1_arg.tipoId,"cc")!=0 && strcmp(registrarpersonal_1_arg.tipoId,"ti")!=0 && strcmp(registrarpersonal_1_arg.tipoId,"pp")!=0){
                                es_valido=0;
                            }
                            
                            printf("\nIngrese el id: ");
                            if(scanf("%i", &registrarpersonal_1_arg.id) != 1){
                                es_valido=0;
                            }
                            
                            clear_newlines();
                            printf("\nIngrese el nombre completo: ");
                            fgets(registrarpersonal_1_arg.nombreCompleto, MAXNOM, stdin);
                            registrarpersonal_1_arg.nombreCompleto[strlen(registrarpersonal_1_arg.nombreCompleto)-1]=' ';//Quita el \n
                            if(esAlfanumerica(registrarpersonal_1_arg.nombreCompleto)){
                                es_valido = 0;
                            }
                            
                            printf("\n1.-recepcionista-administrador\n");
                            printf("2.-medico especialista\n");
                            printf("3.-psicologa\n");
                            printf("4.-fisioterapeuta\n");
                            printf("Escoja un valor para la ocupación: ");
                            scanf("%d", &op2);
                            clear_newlines();
                            if(op2<1 || op2>4){
                                es_valido=0;
                            }else if(op2==1){
                                strcpy(registrarpersonal_1_arg.ocupacion, "recepcionista-admin");
                            }else if(op2==2){
                                strcpy(registrarpersonal_1_arg.ocupacion, "medico especialista");
                            }else if(op2==3){
                                strcpy(registrarpersonal_1_arg.ocupacion, "psicologa");
                            }else if(op2==4){
                                strcpy(registrarpersonal_1_arg.ocupacion, "fisioterapeuta");
                            }
                            
                            //fgets(registrarpersonal_1_arg.ocupacion, MAXDAT, stdin);
                            int flag1=0, flag2=0;
                            do{
                                printf("\nIngrese el usuario: ");
                                scanf("%s", &registrarpersonal_1_arg.usuario);
                                if(strlen(registrarpersonal_1_arg.usuario)<8){
                                    printf("** El usuario debe tener mínimo 8 caracteres alfanuméricos.**");
                                }else{
                                    flag1=1;
                                }
                            }while(flag1==0);
                            
                            do{
                                printf("\nIngrese la contraseña: ");
                                scanf("%s", &registrarpersonal_1_arg.clave);
                                if(strlen(registrarpersonal_1_arg.clave)<8){
                                    printf("** La contraseña debe tener mínimo 8 caracteres alfanuméricos.**");
                                }else{
                                    flag2=1;
                                }
                            }while(flag2==0);
                            
                            if(es_valido==1){
                                result_1 = registrarpersonal_1(&registrarpersonal_1_arg, clnt);
                                if (result_1 == (bool_t *) NULL) {
                                    clnt_perror (clnt, "call  REGISTRAR PERSONAL failed");
                                }else if(*result_1==TRUE){
                                    printf("\n**Personal registrado exitósamente**");
                                }else if(*result_1==FALSE){
                                    printf("\n**Personal NO registrado, se alcanzó la cantidad máxima de personal a registrar**");
                                }
                            }else{
                                printf("\n**Personal NO registrado, error en el formato de los datos ingresados**");
                            }

                            
                        break;
                        
                        case 2:
                            printf("\n===== Consultar  Personal =====\n");
                            printf("Por favor ingrese el id del usuario: ");
                            scanf("%d", &consultarpersonal_1_arg);
                            clear_newlines();
                            result_2 = consultarpersonal_1(&consultarpersonal_1_arg, clnt);
                            if (result_2 == (datos_personal *) NULL) {
                                clnt_perror (clnt, "call CONSULTAR PERSONAL failed");
                            }else if(result_2->id==0){
                                printf("\n**Personal NO encontrado**");
                            }else {
                                printf("\nTipo de identificación[cc, ti, pp]: %s\n", result_2->tipoId);
                                printf("ID: %d\n", result_2->id);
                                printf("Nombre completo: %s\n", result_2->nombreCompleto);
                                printf("Ocupación: %s\n", result_2->ocupacion);
                                printf("Usuario: %s\n", result_2->usuario);
                                //printf("Contraseña: %s\n", result_2->clave);
                            }
                            
                        break;
                    }//fin switch case de Menu Admin
                }while(op1 != 3);
                
            }else if(*result_3==TRUE){
                printf("\nPor favor ingrese el id del usuario: ");
                scanf("%d", &consultarpersonal_1_arg);
                clear_newlines();
                result_2 = consultarpersonal_1(&consultarpersonal_1_arg, clnt);
                if (result_2 == (datos_personal *) NULL) {
                    clnt_perror (clnt, "call CONSULTAR PERSONAL failed");
                }
                //printf("\nLa ocupacion del usuario es : %s\n", result_2->ocupacion);
                if((strcmp(result_2->ocupacion,"recepcionista-admin"))==0){
                    do{
                        printf("\n\n======== Menú R-Admin =========\n");
                        printf("* 1.-Registrar paciente       *\n");
                        printf("* 2.-Consulta paciente        *\n");
                        printf("* 3.-Salir                    *\n");
                        printf("===============================\n");
                        printf("Seleccione una opcion: ");
                        scanf("%d", &op);
                        clear_newlines();
                    }while(op != 3);
                    
                }else if((strcmp(result_2->ocupacion,"medico especialista"))==0 || (strcmp(result_2->ocupacion,"psicologa"))==0){
                    do{
                        printf("\n\n======= Menú Valoracion =======\n");
                        printf("* 1.-Valorar paciente         *\n");
                        printf("* 2.-Consultar paciente       *\n");
                        printf("* 3.-Salir                    *\n");
                        printf("===============================\n");
                        printf("Seleccione una opcion: ");
                        scanf("%d", &op);
                        clear_newlines();
                    }while(op != 3);
                    
                }else if((strcmp(result_2->ocupacion,"fisioterapeuta"))==0){
                    do{
                        printf("\n\n====== Menú Seguimiento =======\n");
                        printf("* 1.-Valorar paciente         *\n");
                        printf("* 2.-Seguimiento paciente     *\n");
                        printf("* 3.-Consultar paciente       *\n");
                        printf("* 4.-Salir                    *\n");
                        printf("===============================\n");
                        printf("Seleccione una opcion: ");
                        scanf("%d", &op);
                        clear_newlines();
                    }while(op != 4);
                    
                }
            }else if(*result_3==FALSE){
                //printf("\nNo se ha registrado ningún usuario con esas credenciales.\n");
                printf("\n**El personal %s no está autorizado para ingresar al sistema.**", username);
                printf("\n**Verificar que el usuario y la clave sean las correctas.**");
            }
			break;//fin case 1 de Menu Inicio

			case 2:
                printf("\nExit...\n");
			break;
			
		}//fin switch case de Menu Inicio
        
	}while(op != 2);//fin do while principal

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

/**
 * Funcion que va despues de cada scanf en el que se lea numeros
 * Sirve para que no se salte los fgets
 */
void clear_newlines(void)
{
    int c;
    do
    {
        c = getchar();
    } while (c != '\n' && c != EOF);
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_personal_1 (host);
exit (0);
}
