/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONPERSONAL_H_RPCGEN
#define _GESTIONPERSONAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30
#define MAXDAT 20
#define MAXTIPOID 4

struct datos_personal {
	char tipoId[MAXTIPOID];
	int id;
	char nombreCompleto[MAXNOM];
	char ocupacion[MAXDAT];
	char usuario[MAXDAT];
	char clave[MAXDAT];
};
typedef struct datos_personal datos_personal;

struct datos_credencial {
	char usuario[MAXDAT];
	char clave[MAXDAT];
};
typedef struct datos_credencial datos_credencial;

#define gestion_personal 0x20000021
#define gestion_personal_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrarPersonal 1
extern  bool_t * registrarpersonal_1(datos_personal *, CLIENT *);
extern  bool_t * registrarpersonal_1_svc(datos_personal *, struct svc_req *);
#define consultarPersonal 2
extern  datos_personal * consultarpersonal_1(int *, CLIENT *);
extern  datos_personal * consultarpersonal_1_svc(int *, struct svc_req *);
#define abrirSesion 3
extern  bool_t * abrirsesion_1(datos_credencial *, CLIENT *);
extern  bool_t * abrirsesion_1_svc(datos_credencial *, struct svc_req *);
extern int gestion_personal_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarPersonal 1
extern  bool_t * registrarpersonal_1();
extern  bool_t * registrarpersonal_1_svc();
#define consultarPersonal 2
extern  datos_personal * consultarpersonal_1();
extern  datos_personal * consultarpersonal_1_svc();
#define abrirSesion 3
extern  bool_t * abrirsesion_1();
extern  bool_t * abrirsesion_1_svc();
extern int gestion_personal_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos_personal (XDR *, datos_personal*);
extern  bool_t xdr_datos_credencial (XDR *, datos_credencial*);

#else /* K&R C */
extern bool_t xdr_datos_personal ();
extern bool_t xdr_datos_credencial ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONPERSONAL_H_RPCGEN */
